languange: python
python:
    - "2.7"
addons:
    postgresql: "9.3"
sudo: required
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - sudo pip install -r requirements.txt
before_script:
    - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
    - psql -d travis_ci_test -c 'CREATE EXTENSION postgis' -U postgres
    - cd avipost
script:
    coverage run --source='.' manage.py test --settings=avipost.settings.travis_ci
after_success:
    coveralls

